config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resource :location, only: [:show, :update]
      resource :password, only: [:update]
      resource :profile, only: [:show, :update]
      resource :session, only: [:create, :destroy]
      resources :alerts, only: [:create]
    end
  end

  get 'auth/edit', to: redirect('/users')
  devise_for :users, path: 'auth', controllers: {
    registrations: 'users/registrations'
  }

  post 'pusher/auth', to: 'pusher#auth'

  resource :dashboard
  resource :channels
  resources :alerts
  resources :users, except: [:edit, :update] do
    namespace :permissions do
      resource :monitor, only: [:update, :destroy]
      resource :alert, only: [:update, :destroy]
    end
  end

  scope module: 'users' do
    resources :profiles, only: [:update]
    resources :locations, only: [:update]
    resources :emails, only: [:update]
    resources :passwords, only: [:update]
  end


  root 'pages#index'
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:guest, :user, :moderator, :admin, :root]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  default_scope { order("created_at DESC") }

  acts_as_mappable

  belongs_to :company

  # As a company worker
  has_many :issued_alerts, class_name: "Alert", foreign_key: "user_id", dependent: :destroy

  has_secure_token :access_token

  def name
    [self.first_name, self.last_name].compact.join(" ")
  end

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/users/emails_controller.rb
class Users::EmailsController < ApplicationController
  def update
    @user = policy_scope(User).find(params[:id])
    @email = EmailForm.new(@user)

    if @email.update(permitted_attributes(Email))
      flash[:notice] = "Recibirá un correo con instrucciones para confirmar su nueva dirección de correo electrónico"
      redirect_to user_path(@user)
    else
      flash[:danger] = "No se ha podido actualizar su cuenta de correo electrónico"
      redirect_to user_path(@user)
    end
  end
end

app/controllers/users/locations_controller.rb
class Users::LocationsController < ApplicationController
  def update
    @user = policy_scope(User).find(params[:id])
    @location = LocationForm.new(@user)
    authorize @location

    if @location.update(permitted_attributes(Location))
      flash[:notice] = "Datos guardados"
      redirect_to user_path(@user)
    else
      redirect_to user_path(@user)
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < ApplicationController
  def update
    @user = policy_scope(User).find(params[:id])
    @password = SecretForm.new(@user)

    if @password.update(permitted_attributes(Password))
      bypass_sign_in(@user)
      flash[:notice] = "Su contraseña ha sido actualizada"
      redirect_to user_path(@user)
    else
      flash[:danger] = "No se ha podido actualizar su contraseña"
      redirect_to user_path(@user)
    end
  end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  def update
    @user = policy_scope(User).find(params[:id])
    @profile = ProfileForm.new(@user)
    authorize @profile

    if @profile.update(permitted_attributes(Profile))
      flash[:notice] = "Datos guardados"
      redirect_to user_path(@user)
    else
      redirect_to user_path(@user)
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)
    create_company

    resource.role = :admin
    resource.company_id = @company.id
    resource.save

    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      @company.destroy!
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up) do |user_params|
  #     user_params.permit(:email,
  #                        :password,
  #                        :password_confirmation,
  #                        company_attributes: [:name])
  #   end
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end

private

  def create_company
    @company = Company.new(name: "My Company")
    @company.save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:destroy, :show]

  def index
    authorize User
    @users = policy_scope(User).page(params[:page])
  end

  def new
    authorize User
    @user_form = UserForm.new
  end

  def create
    @user_form = UserForm.new(User.new(company_id: current_company.id))

    authorize @user_form

    if @user_form.submit(permitted_attributes(User))
      flash[:success] = "Email sent to <strong>#{@user_form.email}</strong>."
      redirect_to user_path(@user_form.user)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def show
    authorize @user, :show?
    @profile = ProfileForm.new(@user)
    @location = LocationForm.new(@user)
    @email = EmailForm.new(@user)
    @password = SecretForm.new(@user)
  end

  def destroy
    authorize @user
    @user.destroy
    redirect_to users_path
  end

private

  def set_user
    @user = policy_scope(User).find(params[:id])
  end
end

app/views/users/_email_form.html.slim
= form_for(@email) do |f|
  .form-group.row
    = f.label :email, 'Correo electrónico', class: 'col-sm-2 col-form-label text-right'
    .col-sm-10
      = f.email_field :email, class: 'form-control'
      - if @email.user.pending_reconfirmation?
        small.form-text.text-success Correo #{@email.user.unconfirmed_email} en espera de confirmación.

  .form-group.row
    = f.label :current_password, 'Contraseña actual', class: 'col-sm-2 col-form-label text-right'
    .col-sm-10
      = f.text_field :current_password, class: 'form-control'
      small.form-text.text-muted Para actualizar el correo electrónico es necesario confirmar con su contraseña.

  .form-grou
    = f.submit 'Guardar', class: 'btn btn-success'

app/views/users/_geo_form.html.slim
= form_with(model: @geo, url: location_path, id: 'worker_geo') do |f|
  .form-group.row
    = f.label :lat, 'Latitud', class: 'col-sm-2 col-form-label text-right'
    .col-sm-10
      = f.text_field :lat, class: 'form-control', autocomplete: 'off'

  .form-group.row
    = f.label :lng, 'Longitud', class: 'col-sm-2 col-form-label text-right'
    .col-sm-10
      = f.text_field :lng, class: 'form-control', autocomplete: 'off'

  = f.submit 'Guardar', class: 'btn btn-success', autocomplete: 'off'

app/views/users/_profile_form.html.slim
= form_with(model: @profile, url: profile_path, id: 'worker_profile') do |f|
  .form-group.row
    = f.label :first_name, 'Nombre', class: 'col-sm-2 col-form-label text-right'
    .col-sm-10
      = f.text_field :first_name, class: 'form-control', autofocus: true, autocomplete: 'off'

  .form-group.row
    = f.label :last_name, 'Apellidos', class: 'col-sm-2 col-form-label text-right'
    .col-sm-10
      = f.text_field :last_name, class: 'form-control', autocomplete: 'off'

  = f.submit 'Guardar', class: 'btn btn-success'

app/views/users/_user.html.slim
tr id="user_#{user.id}"
  td style="width: 50px;"
    = gravatar user, height: 38, class: 'mr-3 rounded-3'

  td style="width: 220px;"
    h6.mt-0.mb-0
      = user.name.present? ? user.name : "Usuario inactivo"
    p.mb-0.text-muted = user.email

  td style="width: 140px;" class="align-middle text-center"
    - if user.admin?
      span.badge.badge-danger Administrador
    - elsif user.moderator?
      span.badge.badge-warning Moderador
    - else
      span.badge.badge-primary Usuario

  td class="align-middle text-center" style="width: 140px;"
    = toggle_monitor_permission(user)

  td class="align-middle text-center" style="width: 140px;"
    = toggle_alert_permission(user)

  td class="align-middle text-right"
    a href="#" class="btn btn-danger btn-sm" role="button" Eliminar

app/views/users/index.html.slim
.col-10.mb-3
  .d-flex.flex-row
    = form_for :search, html: { class: 'w-100 mr-3' } do |f|
      = f.text_field :keywork, class: 'form-control', placeholder: 'Buscar por nombre o correo electrónico'

    = link_to 'Nuevo Usuario',
              new_user_path,
              class: 'btn btn-success'
.col-10.mb-3
  nav.nav.nav-pills
    = link_to users_path, class: 'nav-link active' do
      | Todos
      span.ml-3.badge.badge-light = @users.count
    a.nav-link href="#" Administradores

.col-10
  table.table
    thead
    tbody
      = render @users

.col-10
  = paginate @users

app/views/users/new.html.slim
.col-10
  h5 Nuevo Usuario

.col-10.mt-3
  = form_for(@user_form) do |f|
    .form-group.row
      = f.label :email, class: 'col-sm-2 col-form-label text-right'
      .col-sm-10
        = f.text_field :email, class: 'form-control', autocomplete: 'off', autofocus: true
        small.form-text.text-muted Solo puede agregar correos electrónicos que no se encuentren registrados en otras compañias.

    hr.mt-4
    = link_to 'Cancelar', users_path, class: 'btn btn-outline-secondary float-right'
    = f.submit 'Agregar Usuario', class: 'btn btn-success'

app/views/users/show.html.slim
.col-10
  .row.mb-5
    .col-12
      h5 Perfil
      hr.mt-0

    .col-10.mt-2
      = render 'users/profiles/form'

    .col-2
      p.mb-2 Imagen de perfil
      = gravatar @user, class: 'rounded-3 w-100', height: 204

      div.mt-3
        = link_to 'Cambiar imagen',
                  'http://es.gravatar.com/emails/',
                  class: 'btn btn-outline-secondary btn-block',
                  target: '_blank'

  .row.mb-5
    .col-12
      h5 Localización
      hr.mt-0

    .col-12.mt-2
      = render 'users/locations/form'

  .row.mb-5
    .col-12
      h5 Cambiar correo electrónico
      hr.mt-0

    .col-12.mt-2
      = render 'users/emails/form'

  .row.mb-5
    .col-12
      h5 Cambiar contraseña
      hr.mt-0

    .col-12.mt-2
      = render 'users/passwords/form'

    .col-12.mt-5
      h5 Eliminar cuenta
      hr.mt-0

    .col-12
      p
        ' Una vez que se elimina el trabajador, todos sus datos asociados también son removidos
        ' y no hay forma de recuperarlos. Por favor, tenga precaución.

      = link_to 'Eliminar trabajador',
                user_path(@user),
                method: :delete,
                data: { confirm: '¿Eliminar?' },
                class: 'btn btn-danger'