config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resource :location, only: [:show, :update]
      resource :password, only: [:update]
      resource :profile, only: [:show, :update]
      resource :session, only: [:create, :destroy]
      resources :alerts, only: [:create]
    end
  end

  get 'auth/edit', to: redirect('/users')
  devise_for :users, path: 'auth', controllers: {
    registrations: 'users/registrations'
  }

  post 'pusher/auth', to: 'pusher#auth'

  resource :dashboard
  resource :channels
  resources :alerts
  resources :users, except: [:edit, :update] do
    namespace :permissions do
      resource :monitor, only: [:update, :destroy]
      resource :alert, only: [:update, :destroy]
    end
  end

  scope module: 'users' do
    resources :profiles, only: [:update]
    resources :locations, only: [:update]
    resources :emails, only: [:update]
    resources :passwords, only: [:update]
  end


  root 'pages#index'
end

app/views/shared/_auth_links.html.slim
div class="my-lg-0 ml-auto" id="user-links"
  = link_to 'Sign In',
            new_user_session_path,
            class: 'text-light font-weight-bold my-2 my-sm-0 mr-2'

  span.navbar-text.mr-2 or

  = link_to 'Sign Up',
            new_user_registration_path,
            class: 'text-light font-weight-bold my-2 my-sm-0'

app/views/shared/_company_header.html.slim
.container.mt-4.mb-3
  .row
    .col-12
      h5 = company.name

app/views/shared/_footer.html.slim
footer.container.mt-4
  .row
    .col-12
      hr.mt-0
      div.footer-content.my-4
        ul.list-inline
          li.list-inline-item.mr-3
            small.text-muted &copy; 2017 Spectre, Inc.
          li.list-inline-item.mr-3
            = link_to 'Términos', root_path, class: 'small'
          li.list-inline-item.mr-3
            = link_to 'Privacidad', root_path, class: 'small'
          li.list-inline-item.mr-3
            = link_to 'Ayuda', root_path, class: 'small'
          li.list-inline-item.mr-3
            = link_to 'Contacto', root_path, class: 'small'
          li.list-inline-item.mr-3
            = link_to 'Acerca', root_path, class: 'small'

app/views/shared/_sidebar.html.slim
nav.sidebar.bg-dark.d-flex.flex-column
  p.h5.text-light.font-weight-normal.my-4.ml-3.d-flex.align-items-center
    = octicon 'eye', height: 32, class: 'mr-2'
    span.pl-1.text-no-select Spectre

  div class="divider"

  .nav.nav-pills.flex-column
    = sidebar_link url: dashboard_path,
                   icon: 'dashboard',
                   name: 'Actividad',
                   controller: 'dashboards'

    - if policy(User).index?
      = sidebar_link url: users_path,
                     icon: 'organization',
                     name: 'Usuarios'

    = sidebar_link url: alerts_path,
                   icon: 'alert',
                   name: 'Alertas'

  div class="divider"

  .nav.nav-pills.flex-column
    = sidebar_link url: root_path,
                   icon: 'tools',
                   name: 'Opciones'

    = sidebar_link url: root_path,
                   icon: 'question',
                   name: 'Ayuda'

    = sidebar_link url: destroy_user_session_path,
                   icon: 'sign-out',
                   name: 'Salir',
                   method: :delete

  = link_to root_path, class: 'user-avatar px-3 py-3 d-flex align-items-center mt-auto' do
    = gravatar current_user, class: 'mr-3 rounded-3', height: 28
    span.text-light = current_user.name