config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resource :location, only: [:show, :update]
      resource :password, only: [:update]
      resource :profile, only: [:show, :update]
      resource :session, only: [:create, :destroy]
      resources :alerts, only: [:create]
    end
  end

  get 'auth/edit', to: redirect('/users')
  devise_for :users, path: 'auth', controllers: {
    registrations: 'users/registrations'
  }

  post 'pusher/auth', to: 'pusher#auth'

  resource :dashboard
  resource :channels
  resources :alerts
  resources :users, except: [:edit, :update] do
    namespace :permissions do
      resource :monitor, only: [:update, :destroy]
      resource :alert, only: [:update, :destroy]
    end
  end

  scope module: 'users' do
    resources :profiles, only: [:update]
    resources :locations, only: [:update]
    resources :emails, only: [:update]
    resources :passwords, only: [:update]
  end


  root 'pages#index'
end

app/models/alert.rb
class Alert < ApplicationRecord
  enum state: { created: 0, opened: 4, closed: 10 }
  belongs_to :company
  belongs_to :issuing, class_name: "User", foreign_key: "user_id"
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :authenticate_user!

  def index
    @alerts = current_company.alerts.includes(:issuing)
  end
end

app/controllers/api/v1/alerts_controller.rb
class Api::V1::AlertsController < Api::V1::ApiControllerBase
  def create
    @alert = AlertForm.new(current_user)

    if @alert.update(permitted_attributes(Alert))
      render json: "", status: :created
    else
      head :unprocessable_entity
    end
  end
end

app/controllers/permissions/alerts_controller.rb
class Permissions::AlertsController < ApplicationController
  before_action :set_user

  def update
    @user.update_attribute(:create_alert, true)
  end

  def destroy
    @user.update_attribute(:create_alert, false)
  end

private

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/permissions/alerts_helper.rb
module Permissions::AlertsHelper
  def toggle_alert_permission(user)
    method = user.create_alert? ? "DELETE" : "PATCH"
    css = "btn btn-sm "
    css << (user.create_alert? ? "btn-success" : "btn-secondary")

    link_to "Alertas",
            user_permissions_alert_path(user),
            id: "toggle_alert_permission_#{user.id}",
            class: css,
            method: method,
            remote: true,
            data: { 'disable-with': "Guardando..." }
  end
end

app/views/alerts/_alert.html.slim
tr
  td style="width: 120px;"
    - if alert.opened?
      span.badge.badge-success Abierto
    - else
      span.badge.badge-danger Cerrado

  td style="width: 140px;"
    = link_to "##{alert.id}", alert_path(alert)
    span.mx-2 por
    = link_to user_path(alert.issuing) do
      = gravatar alert.issuing,
                 width: 20,
                 height: 20,
                 class: 'rounded-3',
                 title: alert.issuing.name,
                 alt: alert.issuing.name

  td style="width: 200px;"
    span class="d-inline-block text-truncate" style="max-width: 150px;" = alert.text

  td
  td

app/views/alerts/index.html.slim
.col-10.mb-3
  nav.nav.nav-pills
    = link_to users_path, class: 'nav-link active' do
      | Todos
      span.ml-3.badge.badge-light 0
    a.nav-link href="#" Atendidos
    a.nav-link href="#" Por atender

.col-10
  table.table
    thead
      tr
        th Estado
        th Alerta
        th Guardias
        th Comentario
        th
    tbody
      = render @alerts